"use client";
import Header from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import { useState } from 'react'
import MenuModal from '@/components/MenuModal';

const inter = Inter({ subsets: ['latin'] })

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [visible, setVisible] = useState(false);

  function onVisible(){
    visible === true ? setVisible(false) : setVisible(true);
    console.log(visible);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="w-full m-auto px-2 max-md:px-6 max-w-5xl">
        <Header visible={visible} onVisible={onVisible}/>
          {children}
          {visible === true ? <MenuModal onVisible={onVisible}/> : <></>}
        <Footer />
      </div>
      </body>
    </html>
  )
}
